import {initTrends} from './trends.js';
import {safeUrl, elapsedDays, deliveryLabel, filterCards, cardKeywords} from './catalog.mjs';
import {initAutomation} from './automation.js';
const $ = selector => document.querySelector(selector);
const PAGE_SIZE = 12;
const state = {cards:[], filtered:[], page:1, favorites:new Set(), onlyFavorites:false, token:null, bootstrap:null, auto:false,catalogSignature:null,lastCatalogPoll:0,keywordScope:null};
try {const saved=JSON.parse(localStorage.getItem('jw.meta-ads.favorites')||'[]'); if(Array.isArray(saved)) state.favorites=new Set(saved.filter(x=>typeof x==='string'));} catch {}
function node(tag, cls, text) {const el=document.createElement(tag); if(cls)el.className=cls; if(text!==undefined)el.textContent=text; return el;}
function toast(message) {$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2600);}
function date(value) {const d=new Date(value);return Number.isNaN(d.getTime())?'확인되지 않음':d.toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'});}
function anchor(text,url,cls='') {const a=node('a',cls,text);a.href=safeUrl(url)||'#';a.target='_blank';a.rel='noopener noreferrer';return a;}
function saveButton(card, detailed=false) {const b=node('button',detailed?'button compact':'save');b.type='button';const on=state.favorites.has(card.id);b.textContent=detailed?(on?'★ 저장됨':'☆ 광고 저장'):(on?'★':'☆');b.setAttribute('aria-label',`${card.advertiser} 광고 ${on?'저장 취소':'저장'}`);b.setAttribute('aria-pressed',String(on));b.dataset.save=card.id;b.addEventListener('click',()=>{state.favorites.has(card.id)?state.favorites.delete(card.id):state.favorites.add(card.id);try{localStorage.setItem('jw.meta-ads.favorites',JSON.stringify([...state.favorites]));}catch{toast('이 브라우저에서는 저장이 이번 방문 동안만 유지됩니다.');}document.querySelectorAll('[data-save]').forEach(button=>{const active=state.favorites.has(button.dataset.save);button.setAttribute('aria-pressed',String(active));const savedCard=state.cards.find(c=>c.id===button.dataset.save);if(savedCard)button.setAttribute('aria-label',`${savedCard.advertiser} 광고 ${active?'저장 취소':'저장'}`);button.textContent=button.classList.contains('save')?(active?'★':'☆'):(active?'★ 저장됨':'☆ 광고 저장');});$('#favorite-count').textContent=state.favorites.size;if(state.onlyFavorites){render();$('#favorite-toggle').focus({preventScroll:true});}});return b;}
function image(url,alt){const img=node('img');img.src=safeUrl(url);img.alt=alt;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>{img.alt='미리보기를 불러올 수 없습니다';img.classList.add('image-error');},{once:true});return img;}
function cardView(card){const article=node('article','ad-card');const visual=node('div','creative');const open=node('button','creative-open');open.type='button';open.setAttribute('aria-label',`${card.advertiser} 광고 상세 보기`);const video=card.media.find(m=>m.type==='video');const cover=video?.poster||card.media.find(m=>m.type==='image')?.url;open.append(cover?image(cover,`${card.advertiser} 광고 소재`):node('span','loading','미리보기 없음'));open.addEventListener('click',()=>showDetail(card));visual.append(open,node('span','media-label',`${video?'▶ VIDEO':'IMAGE'}${card.media.length>1?' · '+card.media.length+'개 소재':''}`),saveButton(card));const body=node('div','card-content');body.append(node('h3','card-advertiser',card.advertiser||'광고주 미확인'),node('p','card-text',card.text||'광고 문구 없음'));const meta=node('div','card-meta');meta.append(node('span',`delivery-${card.deliveryStatus||'unknown'}`,deliveryLabel(card)));meta.title=`상태 확인: ${date(card.statusCheckedAt||card.collectedAt)}`;if(safeUrl(card.landingUrl))meta.append(anchor(`${card.domain||'랜딩페이지'} ↗`,card.landingUrl));body.append(meta);article.append(visual,body);return article;}
function readFilters(){return {q:$('#search').value,keyword:$('#keyword').value,keywordIds:state.keywordScope?.keyword===$('#keyword').value?state.keywordScope.ids:[],ids:state.keywordScope?.keyword===$('#keyword').value&&state.keywordScope.mode==='notes'?state.keywordScope.ids:null,advertiser:$('#advertiser').value,domain:$('#domain').value,media:$('#media-type').value,delivery:$('#delivery-status').value,days:Math.max(0,Number($('#days-min').value)||0),sort:$('#sort').value,favorites:state.onlyFavorites};}
function render(){state.filtered=filterCards(state.cards,readFilters(),state.favorites);const totalPages=Math.max(1,Math.ceil(state.filtered.length/PAGE_SIZE));state.page=Math.min(Math.max(state.page,1),totalPages);const target=$('#cards');target.replaceChildren();target.setAttribute('aria-busy','false');const slice=state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE);if(!slice.length){const empty=node('div','empty');empty.append(node('strong','',state.onlyFavorites?'저장한 광고가 없습니다':'일치하는 광고가 없습니다'),node('p','',state.onlyFavorites?'마음에 드는 광고의 별표를 눌러보세요.':'검색어나 필터를 바꿔보세요.'));target.append(empty);}else target.append(...slice.map(cardView));$('#result-count').textContent=`${state.keywordScope?.keyword===$('#keyword').value&&state.keywordScope.label?state.keywordScope.label+' · ':''}${state.filtered.length}개 광고 · ${state.page} / ${totalPages} 페이지`;$('#page-info').textContent=`${state.page} / ${totalPages}`;$('#previous').disabled=state.page===1;$('#next').disabled=state.page===totalPages;$('#favorite-count').textContent=state.favorites.size;$('#total-count').textContent=state.cards.length;}
function updateOptions(){for(const [selector,field,label]of[['#keyword','keyword','전체 키워드'],['#advertiser','advertiser','전체 광고주'],['#domain','domain','전체 도메인']]){const select=$(selector),previous=select.value;select.replaceChildren(new Option(label,''));[...new Set((field==='keyword'?state.cards.flatMap(cardKeywords):state.cards.map(c=>c[field])).filter(Boolean).concat(field==='keyword'&&state.keywordScope?[state.keywordScope.keyword]:[]))].sort((a,b)=>a.localeCompare(b,'ko')).forEach(value=>select.add(new Option(value,value)));if([...select.options].some(o=>o.value===previous))select.value=previous;}}
function showDetail(card){const wrap=node('div','detail-grid'),media=node('div','detail-media'),copy=node('div','detail-copy');for(const m of card.media){if(!safeUrl(m.url))continue;if(m.type==='video'){const v=node('video');v.controls=true;v.playsInline=true;v.preload='metadata';v.src=safeUrl(m.url);if(m.poster)v.poster=safeUrl(m.poster);v.addEventListener('play',()=>media.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause();}));media.append(v);}else media.append(image(m.url,`${card.advertiser} 광고 이미지`));}const title=node('h2','',card.advertiser);title.id='detail-title';copy.append(node('p','eyebrow',card.keyword||'AD REFERENCE'),title,node('p','detail-text',card.text||'등록된 광고 문구가 없습니다.'));const dl=node('dl','detail-facts');for(const [label,value]of[['광고 시작일',date(card.startedAt)],['수집일',date(card.collectedAt)],['상태 확인일',date(card.statusCheckedAt||card.collectedAt)],[card.durationBasis==='detected'?'종료 감지일':'광고 종료일',card.deliveryStatus==='ended'?date(card.endedAt||card.endedDetectedAt):'종료 확인 기록 없음'],['게재 기록',deliveryLabel(card)],['도메인',card.domain||'미확인'],['광고 ID',card.id]])dl.append(node('dt','',label),node('dd','',value));copy.append(dl);const queries=cardKeywords(card);if(queries.length)copy.append(node('p','detail-queries',`수집 검색어 · ${queries.join(' · ')}`));const actions=node('div','detail-actions');actions.append(saveButton(card,true));if(safeUrl(card.landingUrl))actions.append(anchor('랜딩페이지 ↗',card.landingUrl,'button compact'));if(/^\d+$/.test(card.id))actions.append(anchor('Meta 원본 ↗',`https://www.facebook.com/ads/library/?id=${card.id}`,'button compact'));copy.append(actions);const assets=node('div','asset-downloads');assets.append(node('h3','',`저장된 소재 ${card.media.length}개`));card.media.forEach((m,i)=>{const url=safeUrl(m.url);if(!url)return;const a=anchor(`${m.type==='video'?'영상':'이미지'} ${i+1} 원본 열기 ↗`,url,'asset-link');assets.append(a);});copy.append(assets);wrap.append(media,copy);$('#detail-content').replaceChildren(wrap);$('#detail').showModal();}
async function api(path,method='GET',body,retry=true){const response=await fetch(`/api/meta-ads${path}`,{method,cache:'no-store',headers:{...(body?{'Content-Type':'application/json'}:{}),...(state.token?{'X-Meta-Ads-Token':state.token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const data=await response.json();if([401,403].includes(response.status)&&method!=='GET'&&retry&&state.token&&['127.0.0.1','localhost'].includes(location.hostname)){const fresh=await api('/bootstrap');state.token=fresh.token;return api(path,method,body,false);}if(!response.ok)throw new Error(data.error||data.message||'요청을 처리하지 못했습니다.');return data;}
async function load(){const refresh=$('#refresh');refresh.disabled=true;try{let catalog;const isLocal=['127.0.0.1','localhost'].includes(location.hostname);if(isLocal){try{state.bootstrap=await api('/bootstrap');state.token=state.bootstrap.token;state.auto=Boolean(state.bootstrap.status?.autoEnabled);catalog=await api('/cards');}catch{state.bootstrap=null;state.token=null;}}if(!catalog){const response=await fetch('./data/catalog.json',{cache:'no-cache'});if(!response.ok)throw new Error('저장된 광고 자료를 불러오지 못했습니다.');catalog=await response.json();}if(!Array.isArray(catalog.cards))throw new Error('광고 목록 형식이 올바르지 않습니다.');state.catalogSignature=JSON.stringify(catalog.cards);state.lastCatalogPoll=Date.now();state.cards=catalog.cards.filter(c=>c&&typeof c.id==='string'&&Array.isArray(c.media)).map(c=>({...c,media:c.media.filter(m=>m&&['image','video'].includes(m.type)&&safeUrl(m.url))}));updateOptions();render();$('#connection').textContent=state.token?'개인 PC 연결':'공개 아카이브';const dates=state.cards.map(c=>Date.parse(c.collectedAt)).filter(Number.isFinite);const range=dates.length?`${date(Math.min(...dates))} — ${date(Math.max(...dates))}`:'수집 자료 없음';$('#archive-note').textContent=`수집일 ${range} · ${state.token?'수집 관리에서 새 광고를 추가할 수 있습니다.':'저장한 이미지·영상은 이 페이지에서 볼 수 있습니다. 게재 상태는 마지막 확인 시점을 기준으로 표시합니다.'}`;$('#manager-public').hidden=Boolean(state.token);$('#manager-local').hidden=!state.token;initTrends({api,isLocal:Boolean(state.token),cards:()=>state.cards,cardView});initAutomation({api,isLocal:Boolean(state.token)});if(state.token)await renderManager();}catch(error){$('#connection').textContent='불러오기 실패';$('#archive-note').textContent=error.message;$('#cards').replaceChildren(node('div','empty','자료를 불러오지 못했습니다. 새로고침으로 다시 시도해주세요.'));$('#cards').setAttribute('aria-busy','false');}finally{refresh.disabled=false;}}
async function refreshCatalog(){
  if(state.catalogSignature===null||document.hidden||Date.now()-state.lastCatalogPoll<(state.token?15000:60000))return;
  state.lastCatalogPoll=Date.now();
  try{
    let catalog;
    if(state.token)catalog=await api('/cards');
    else {const response=await fetch('./data/catalog.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)return;catalog=await response.json();}
    if(!Array.isArray(catalog.cards))return;
    const signature=JSON.stringify(catalog.cards);if(signature===state.catalogSignature)return;
    state.catalogSignature=signature;
    state.cards=catalog.cards.filter(c=>c&&typeof c.id==='string'&&Array.isArray(c.media)).map(c=>({...c,media:c.media.filter(m=>m&&['image','video'].includes(m.type)&&safeUrl(m.url))}));
    updateOptions();render();window.dispatchEvent(new CustomEvent('meta-ads-catalog-updated'));
    $('#archive-note').textContent=`${state.cards.length}개 광고 · 새 수집 결과와 게재 상태를 반영했습니다. 상태 확인일은 각 광고 상세에서 볼 수 있습니다.`;
  }catch{}
}
async function renderManager(){if(!state.token)return;try{const [competitors,jobs,status]=await Promise.all([api('/competitors'),api('/jobs'),api('/status')]);const focused=document.activeElement;const currentRow=focused?.closest('.competitor-row,.job-row');const focusKey=currentRow?.dataset.row;const focusLabel=focused?.getAttribute('aria-label')||focused?.textContent;state.auto=status.autoEnabled;$('#auto-toggle').setAttribute('aria-pressed',String(state.auto));$('#auto-toggle').textContent=state.auto?'켜짐':'꺼짐';const list=$('#competitor-list');list.replaceChildren();for(const c of (competitors.competitors||[]).filter(c=>!c.trendOnly)){const row=node('div','competitor-row'),text=node('div');row.dataset.row=c.id;text.append(node('strong','',c.name),node('small','',`${c.keyword} · ${c.domain||'전체 도메인'} · ${c.intervalHours||24}시간 간격`));const run=node('button','button compact','수집');run.addEventListener('click',()=>action(async()=>{await api('/collect','POST',{competitorId:c.id,limit:20});toast('수집 대기열에 추가했습니다.');}));const remove=node('button','text-button','삭제');remove.setAttribute('aria-label',`${c.name} 수집 목록 삭제`);remove.addEventListener('click',()=>action(()=>api(`/competitors/${encodeURIComponent(c.id)}`,'DELETE')));row.append(text,run,remove);list.append(row);}if(!list.childNodes.length)list.append(node('p','muted','등록된 수집 목록이 없습니다.'));const jobList=$('#job-list');jobList.replaceChildren();const labels={queued:'대기 중',running:'수집 중',done:'수집 완료',failed:'수집 실패',canceled:'취소됨'};for(const job of (jobs.jobs||[]).slice(0,10)){const row=node('div','job-row'),text=node('div');row.dataset.row=job.id;text.append(node('strong','',`${labels[job.status]||job.status} · ${job.keyword||job.competitorName||'광고 수집'}`),node('small','',job.message||date(job.requestedAt)));row.append(text);if(['queued','running'].includes(job.status)){const cancel=node('button','text-button','취소');cancel.addEventListener('click',()=>action(()=>api(`/jobs/${encodeURIComponent(job.id)}/cancel`,'POST',{})));row.append(cancel);}jobList.append(row);}if(!jobList.childNodes.length)jobList.append(node('p','muted','아직 실행한 작업이 없습니다.'));if(focusKey){const row=[...document.querySelectorAll('[data-row]')].find(el=>el.dataset.row===focusKey);const button=[...(row?.querySelectorAll('button')||[])].find(el=>(el.getAttribute('aria-label')||el.textContent)===focusLabel);button?.focus({preventScroll:true});}if(status.cardCount!==state.cards.length){const catalog=await api('/cards');state.cards=catalog.cards.filter(c=>c&&typeof c.id==='string'&&Array.isArray(c.media)).map(c=>({...c,media:c.media.filter(m=>m&&['image','video'].includes(m.type)&&safeUrl(m.url))}));updateOptions();render();}}catch(error){$('#manager-message').textContent=error.message;}}
async function action(fn){$('#manager-message').textContent='';try{await fn();await renderManager();}catch(error){$('#manager-message').textContent=error.message;}}
$('#search-form').addEventListener('submit',event=>{event.preventDefault();state.page=1;render();});let searchTimer;$('#search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.page=1;render();},180);});for(const id of ['keyword','advertiser','domain','media-type','delivery-status','days-min','sort'])$('#'+id).addEventListener('change',()=>{state.page=1;render();});
$('#reset').addEventListener('click',()=>{state.keywordScope=null;for(const id of ['search','keyword','advertiser','domain','media-type','delivery-status','days-min'])$('#'+id).value='';$('#sort').value='collected';state.page=1;state.onlyFavorites=false;$('#favorite-toggle').setAttribute('aria-pressed','false');render();});$('#favorite-toggle').addEventListener('click',()=>{state.onlyFavorites=!state.onlyFavorites;$('#favorite-toggle').setAttribute('aria-pressed',String(state.onlyFavorites));state.page=1;render();});for(const [id,step]of[['previous',-1],['next',1]])$('#'+id).addEventListener('click',()=>{state.page+=step;render();$('.results-toolbar').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
$('#refresh').addEventListener('click',load);$('#manage-open').addEventListener('click',()=>{$('#manager').showModal();if(state.token)renderManager();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>dialog.querySelectorAll('video').forEach(v=>v.pause()));});
$('#auto-toggle').addEventListener('click',()=>action(()=>api('/settings','POST',{autoEnabled:!state.auto})));$('#competitor-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{await api('/competitors','POST',{name:$('#competitor-name').value.trim(),keyword:$('#competitor-keyword').value.trim(),domain:$('#competitor-domain').value.trim(),intervalHours:Number($('#competitor-interval').value)});$('#competitor-form').reset();toast('수집 목록에 추가했습니다.');});});
$('#export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),cards:state.filtered},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='광고-레퍼런스.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
setInterval(()=>{if(state.token&&$('#manager').open&&!document.hidden)renderManager();refreshCatalog();},5000);load();


$('#filters-toggle').addEventListener('click',()=>{const open=$('.filters').classList.toggle('is-open');$('#filters-toggle').setAttribute('aria-expanded',String(open));$('#filters-toggle').textContent=open?'접기 −':'펼치기 +';});

window.addEventListener('meta-ads-trend-complete', load);
window.addEventListener('meta-ads-filter',event=>{
  for(const id of ['keyword','advertiser','domain','media-type','delivery-status','days-min'])$('#'+id).value='';
  const detail=event.detail||{};state.keywordScope=detail.keyword?{keyword:detail.keyword,ids:Array.isArray(detail.ids)?detail.ids:[],mode:detail.mode||'query',label:detail.label||''}:null;
  updateOptions();if(detail.keyword)$('#keyword').value=detail.keyword;
  if(detail.advertiser)$('#advertiser').value=detail.advertiser;if(detail.domain)$('#domain').value=detail.domain;
  state.onlyFavorites=false;$('#favorite-toggle').setAttribute('aria-pressed','false');$('#search').value=detail.query||'';state.page=1;render();
});
